[package]
name = "cringe-lang"
version = "0.0.0-wip"
edition = "2024"
description = "N/A"
readme = "README.md"
repository = "https://github.com/jonathan-schild/cringe-lang.git"
license = "EUPL-1.2"
publish = false

[dependencies]
env_logger = "0.11.6"
log = "0.4.26"
thiserror = "2.0.12"
